site_name: Particle Docs
site_favicon: favicon.ico
theme: readthedocs
pages:
  - Overview: 'index.md'
  - Getting Started: 'getting-started/system-requirements.md'
  - Commands: 'getting-started/commands.md'
  - Architecture: 'getting-started/architecture.md'
  - Config:
    - Webpack: 'config/webpack.md'
    - Gulp: 'config/gulpfile.md'
    - Linting: 'config/linting.md'
  - Apps:
    - Pattern Lab: 'apps/pl.md'
    - Drupal: 'apps/drupal-requirements.md'
  - FAQ:
    - General: 'faq/general.md'
    - Troubleshooting: 'faq/troubleshooting.md'
    - How to contribute: 'faq/how-to-contribute.md'
  - Appendix:
    - Glossary: 'appendix/glossary.md'
    - Background: 'appendix/background.md'
    - Library: 'appendix/library.md'