site_name: Particle Docs
theme: readthedocs
pages:
  - Overview: 'index.md'
  - Getting Started: 'appendix/system-requirements.md'
  - Commands: 'appendix/commands.md'
  - Architecture: 'appendix/architecture.md'
  - Config:
    - General: 'config/general.md'
    - Webpack: 'config/webpack.md'
    - Gulp: 'config/gulpfile.md'
    - Sass: 'config/sass.md'
    - Linting: 'config/linting.md'
    - Testing: 'config/testing.md'
  - Apps:
    - Pattern Lab: 'apps/pl.md'
    - Drupal: 'apps/drupal.md'
    - Grav: 'apps/grav.md'
    - Adding or Removing: 'apps/general.md'
  - FAQ: 'faq/index.md'
  - Appendix: 'appendix/index.md'
