site_name: Particle Docs
theme: readthedocs
pages:
  - Home: 'index.md'
  - Getting Started:
    - System Requirements: 'getting-started/system-requirements.md'
    - Quickstart: 'getting-started/quickstart.md'
    - Commands: 'getting-started/commands.md'
  - Architecture:
    - Folder Structure: 'architecture/folders.md'
    - Component Structure: 'architecture/components.md'
    - Config Structure: 'architecture/config.md'
  - Development:
    - Coding: 'dev/coding.md'
    - Bundling: 'dev/bundling.md'
    - Task Running: 'dev/task-running.md'
    - Linting: 'dev/linting.md'
    - Testing: 'dev/testing.md'
  - Apps:
    - General: 'apps/general.md'
    - Drupal: 'apps/drupal.md'
    - Pattern Lab: 'apps/pl.md'
    - Grav: 'apps/grav.md'
  - Approach:
    - Sass/CSS: 'approach/styles.md'
    - Javascript: 'approach/js.md'
    - Twig: 'approach/twig.md'
    - Assets: 'approach/assets.md'
  - FAQ:
    - General: 'faq/general.md'
    - Troubleshooting: 'faq/troubleshooting.md'
    - How to contribute: 'faq/how-to-contribute.md'
  - Appendix:
    - Glossary: 'appendix/glossary.md'
    - Library: 'appendix/library.md'