site_name: Phase2 Front End Tools Documentation
site_favicon: favicon.ico
theme: readthedocs
pages:
  - Home: 'index.md'
  - Getting Started:
    - System Requirements: 'getting-started/system-requirements.md'
    - First Steps: 'getting-started/first-steps.md'
    - Drupal Requirements: 'getting-started/drupal-requirements.md'
  - Pattern Lab:
    - Atomic design: 'pattern-lab/atomic.md'
  - Gulp:
    - Config: 'gulp/gulpfile.md'
    - pl Compile: 'gulp/tasks/pl-compile.md'
    - twig namespaces: 'gulp/tasks/twig-namespaces.md'
    - sass to json: 'gulp/tasks/sass-to-json.md'
    - webpack dev server: 'gulp/tasks/wpds.md'
  - Webpack:
    - Config: 'webpack/config.md'
  - FAQ:
    - General: 'faq/general.md'
    - Troubleshooting: 'faq/troubleshooting.md'
    - How to contribute: 'faq/how-to-contribute.md'
  - Appendix:
    - Glossary: 'appendix/glossary.md'
    - Architecture: 'appendix/architecture.md'
    - Background: 'appendix/background.md'
    - Library: 'appendix/library.md'